# Generated by Django 4.1.1 on 2022-09-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_remove_comment_createion_date_comment_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comments_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_of_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
